name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        env:
          SERVER_HOST: ${{secrets.SERVER_HOST}}
          SERVER_USER: ${{secrets.SERVER_USER}}
          SERVER_SSH_KEY: ${{secrets.SERVER_SSH_KEY}}
        if: ${{env.SERVER_HOST && env.SERVER_USER && env.SERVER_SSH_KEY}}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ./overjjangServerChart/
            git pull origin master
            npm install
            pm2 restart server

      - name: Skip deployment in fork
        env:
          SERVER_HOST: ${{secrets.SERVER_HOST}}
          SERVER_USER: ${{secrets.SERVER_USER}}
          SERVER_SSH_KEY: ${{secrets.SERVER_SSH_KEY}}
        if: ${{env.SERVER_HOST == null || env.SERVER_USER == null || env.SERVER_SSH_KEY == null}}
        run: echo "Secrets not found. Skipping deployment."